version: '3'

services:
  db:
    image: mariadb:10.2
    container_name: repository-mysql-db-dev
    #    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: repository
      MYSQL_ROOT_PASSWORD: repoudc
